### ISSUE TITLE
Add a Web UI for gocd.slack.pipelines rules.

### ISSUE THREAD

**Issue by dwijnand** [ashwanthkumar/gocd-slack-build-notifier#7]
We have a large number of pipelines, and a number of teams. Instead of having each team jump into a config file on the server, it would be convenient to be able to change these from the Web UI.

**Comment by mikeparker** [comment]
Is this done or cancelled? We also have lots of pipelines and can't afford to edit the config file all the time. I'm looking for a way to specify the channel for pipelines to notify on a per pipeline basis (e.g. environment variable)

**Comment by ashwanthkumar** [comment]
I never got around implementing this :( Any sort of help will be appreciated.

**Comment by juhasipo** [comment]
@ashwanthkumar I've been working on a version of this kind of feature where you could configure notification settings to pipelines via environment variables. The idea is to let global settings for all pipelines to be configured via plugin settings which then could be overridden with the pipeline environment variables. The variables would be `GO_SLACK_CHANNEL`, `GO_SLACK_STAGES` and `GO_SLACK_STATUSES`.

This change will require admin username and password to be configured for the plugin so that the plugin can get the pipeline configurations. Also it will require require GoCD version 15.3 or above which added the pipeline config API.

I have already implemented the basic plugin settings and the environment variable support. I still need to implement the global pipeline configurations and test it with my own GoCD pipelines.

**Comment by ashwanthkumar** [comment]
@juhasipo If we've to set these values from an environment variable, wouldn't that mean a lot of changes for existing pipelines?

**Comment by ashwanthkumar** [comment]
@mikeparker The reason I'm still not convinced on the UI for the rules is that, these sort of files were meant to be managed via configuration management systems like Chef / Ansible. That's how we manage it in our environment. Also these settings are 1 time operations right?. 

Would love to hear on how you manage these settings today and how building a UI help in the course?

**Comment by juhasipo** [comment]
@ashwanthkumar 
We have currently several projects used by different project teams on our GoCD server. With the current way each team would either have to have admin access to the GoCD server or ask the admins to change the configurations for their project pipelines. This change would make it slightly faster for the teams or team's pipeline group admins to manage the configurations themselves and try out which notification level works best for them.

But you're right that usually this is a one time operation and it doesn't require that much effort. And if you are using a configuration management system the file based configuration is the easiest way to handle this.

Using environment variables would require many changes to the existing pipelines if it is not possible to configure them using the suggested global configuration. And configuring the notifications for each pipeline would take some time if done via UI. If there would be both the file and this environment variable based configuration it would give the admins a possibility to configure the global settings via Ansible/Chef while the project pipeline group admins would have the freedom to configure the notification settings by themselves. 

In future once GoCD gets the support for the SCM based pipeline configuration (https://github.com/gocd/gocd/issues/1133) the environment variable based configuration could make it possible to each project team to set the notification settings straight from the SCM.

**Comment by ashwanthkumar** [comment]
Thank you so much for the inputs @juhasipo. I'm re-opening this issue - for others to pitch in.

**Comment by jonwolski** [comment]
@juhasipo, With regard to the following:

> Using environment variables would require many changes to the existing pipelines

I used environment variables for this exact use case, and I found that I rarely needed to update an individual pipeline. In my case, each development team had their own _pipeline group_, so I was able to set the environment variables there instead of on each pipeline. 

For things that were global to _all_ pipelines, I set those environment variables on the Go _environment_. (In my case, all the pipelines that needed to notify slack happened to be in the same environment.)

**Comment by jonwolski** [comment]
FWIW, I don't care for setting my slack password in a config file. I would much rather put this in a "secure environment variable." If nothing else, getting an env var for the password would be helpful.

**Comment by dwijnand** [comment]
I no longer use GoCD, so I don't even know if this is still an issue.
